### ISSUE TITLE
Server crashing issue

### ISSUE THREAD

**Issue by sjdodge123** [sjdodge123/spaceroyale.io#136]
Log dump from dev.spaceroyale.io

[nodemon] starting `node runServer.js`
Detected DEV environment
listening on 0.0.0.0:3000
Guest77787 joined Room 3
Guest77787 left Room 3
Guest65394 joined Room 3
Guest53322 joined Room 3
Room3's game has ended.
Guest53322 wins!
Guest53322 left Room 3
Guest65394 left Room 3
Guest29459 joined Room 3
Guest35198 joined Room 3
/home/ubuntu/spaceroyale.io/server/factory.js:1868
                this.currentDrone.targetShip.enable();
                                            ^

TypeError: Cannot read property 'enable' of null
    at HackingDrone.reset (/home/ubuntu/spaceroyale.io/server/factory.js:1868:31)
    at GameBoard.resetShips (/home/ubuntu/spaceroyale.io/server/factory.js:659:16)
    at Game.start (/home/ubuntu/spaceroyale.io/server/factory.js:200:18)
    at Game.startLobbyTimer (/home/ubuntu/spaceroyale.io/server/factory.js:305:9)
    at Game.checkForGameStart (/home/ubuntu/spaceroyale.io/server/factory.js:289:8)
    at Game.update (/home/ubuntu/spaceroyale.io/server/factory.js:258:9)
    at Room.update (/home/ubuntu/spaceroyale.io/server/factory.js:58:13)
    at Object.exports.updateRooms (/home/ubuntu/spaceroyale.io/server/hostess.js:47:9)
    at Timeout.update [as _onTimeout] (/home/ubuntu/spaceroyale.io/runServer.js:62:11)
    at ontimeout (timers.js:386:14)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by sjdodge123** [comment]
I believe this to be resolved, but leaving it open just in case it shows up again
