### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by sjdodge123** [sjdodge123/spaceroyale.io#144]
Detected DEV environment
listening on 0.0.0.0:3000
Guest87532 joined Room 8
Guest55912 joined Room 8
Guest55912 left Room 8
Room8's game has ended.
Guest87532 left Room 8
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/ubuntu/spaceroyale.io/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    at Socket.<anonymous> (/home/ubuntu/spaceroyale.io/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by sjdodge123** [comment]
Might be useful to implement

https://stackoverflow.com/questions/20210522/nodejs-mysql-error-connection-lost-the-server-closed-the-connection

**Comment by sjdodge123** [comment]
closed in 5f98660
